services:
  jenkins:
    build:
      context: ./jenkins
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  myapp:
    build:
      context: ./app
    ports:
      - "8000:3000"
    depends_on:
      - jenkins

volumes:
  jenkins-data:
